### PR TITLE
1.5 Compatibility for Split Screen

### LINKED ISSUE #60: Many problems in Local (split screen) Co-Op
When another farmer joins in local co-op (split screen), the experience tracker will endlessly repeat experience gain notifications as soon as they join, even though no one is gaining experience. Each character after the first introduces more, so with three players each screen will see repeating experience notifications at two different points on screen, that seem to track the movements (but not actual location) of the other farmers. This seems to lag the game, especially as more local players join.

You can't open the mod's config menu in split screen (clicking the icon does nothing). The icon sometimes moves, but I'm not sure under what circumstances. 

Icons for luck (and probably others) are displayed for each character for every character. So if there are three local players, three luck icons are displayed on each character's (split) screen.

The experience bar for all characters seems to only show the experience progress level of the last player to join (so all three screens see the experience bar of player three).

(Tested using the UI Info Suite unofficial update on SMAPI 3.8.2 develop, as 3.8.1 has other local co-op bugs)

I'm guessing a lot of this can be fixed by using the new `PerScreen<T>`.

### PR DESCRIPTION
**Pull request by DiscipleOfEris**
Fixed issues introduced by 1.5's new Split Screen functionality.
As part of this, fixed compatibility with 1.5's new UI Scale feature.

Split Screen users are constrained to using the same mod options.

Fixed #60

### CODE REVIEW

**Comment by DarkIrata** [comment]
Scaling isn't fixed for the Billboard

**Comment by DiscipleOfEris** [comment]
@DarkIrata It should be fixed now.

**Comment by DarkIrata** [comment]
Checked, works

**Comment by DarkIrata** [comment]
Wubs. Nevermind. It always opens the quests tab. My mistake while testing it

**Comment by DiscipleOfEris** [comment]
@DarkIrata Good catch. Should be good now.

**Comment by Alex-LauChunHung** [comment]
I'm new in Github. So how can I use this?

**Comment by DarkIrata** [comment]
@DiscipleOfEris works.
LGTM 

@Alex-LauChunHung Pull (or Download as ZIP) the Fork (DiscipleOfEris Master Branch) and compile it.

**Comment by velit** [comment]
@DiscipleOfEris I built this and tested it. While the hovering petting hands and Billboard/Calendar buttons work with unsynchronized Game / UI Zoom the Social tab "Track on map" functionality drifts and is offset.

Concretely it is not possible to press the checkmarks on the magnifying glasses directly when Game Zoom differs from UI Zoom.

**Comment by DiscipleOfEris** [comment]
@velit Your stated issue should be fixed with the latest commit.

At the moment, tracking options _cannot_ be different between players in SplitScreen, and if one player clicks a checkbox it will update the option for all players, but if any other player happens to be looking at the Social menu, it'll appear to update the checkbox in the same _visual_ position, rather than for the correct character. Other players must re-open the social tab to see the changes.

**Comment by velit** [comment]
Social tab "Track on map" functionality now works with differing zoom levels. Thanks 👍

**Comment by velit** [comment]
Okay I got a friend to play this evening together. I don't know what scope you're trying to implement this feature but the "Track on map" functionality fully doesn't work for multiplayer farmhands. Previously the farmhand would see NPCs in their homes but it would not update their real location. With current commit NPCs aren't on the map at all for multiplayer farmhands.

**Comment by DiscipleOfEris** [comment]
@velit Can you describe your issue more? Tracking NPC locations on the map in SplitScreen works flawlessly for me with the latest commit.

**Comment by velit** [comment]
Very simply the same feature does not work with multiplayer. Ie. not split-screen but when playing with a friend online. (As I said I'm not sure what scope you're reaching with this feature in the sense that are you even trying to make it work in online multiplayer, but I'm reporting it here nonetheless so the info is shared).

**Comment by DiscipleOfEris** [comment]
@velit Ah, remote multiplayer. I think this commit should fix your issue, but I didn't test it.

**Comment by velit** [comment]
My friend reports that it's now back to the baseline bugged version. Ie. now my remote multiplayer farmhand friend sees the NPCs in their homes in the map but they never move during the day. Only the host has moving NPCs in the map with correctly reported locations. This is now back to the same behaviour as the 1.9.1-unofficial.2-Strobe version from https://stardewcommunitywiki.com/Modding:Mod_compatibility

**Comment by DiscipleOfEris** [comment]
@velit Well at least there's that. I don't have a testing environment set up to support remote multiplayer so I probably won't fix this anytime soon.

**Comment by velit** [comment]
I wanna say you're awesome @DiscipleOfEris. Even if it this would ultimately end up being too much work to fix the fact that you'd go out of your way to set up remote multiplayer locally to try to fix an issue for others is just awesome.

So no matter what happens I want you to know you're appreciated.

**Comment by DiscipleOfEris** [comment]
@velit Well I have a version working in remote multiplayer, but I had to rewrite some stuff and the old mappings from tile/location to map pixel don't apply perfectly anymore. I haven't decided if it's worth my time to fix pixel things, not really the kinda coding I like to do, haha.

**Comment by velit** [comment]
Ah my apologies. My friend and I finished our playthrough and can't really test it anymore.

**Pull request merged**
